# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b828772c65fe76488e1e892b5f3e126b51661886c4c56127ac32c1265461478709f099dda303aa14ba4cb91ba0dfaeb0f52a04f3e0e38260f159336ff59794

test:
  secret_key_base: 9c41c3323dfc99cdaeb6ea1a0e022a191d442d7229f6f2d9bdfcf89bc6b1243793ffbbb40dccc2d22bcc98a0ddce6aaa7dc9fce887fa0d02ee721353c4db5c9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
